//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.bukkitmodders.copycat.config;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for globalSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="globalSettingsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="maxImageWidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="maxImageHeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="blockProfiles">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="blockProfile" type="{http://www.example.org/pluginSettings}blockProfileType" maxOccurs="unbounded"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "globalSettingsType", propOrder = {
    "maxImageWidth",
    "maxImageHeight",
    "blockProfiles"
})
public class GlobalSettingsType {

    protected int maxImageWidth;
    protected int maxImageHeight;
    @XmlElement(required = true)
    protected GlobalSettingsType.BlockProfiles blockProfiles;

    /**
     * Gets the value of the maxImageWidth property.
     * 
     */
    public int getMaxImageWidth() {
        return maxImageWidth;
    }

    /**
     * Sets the value of the maxImageWidth property.
     * 
     */
    public void setMaxImageWidth(int value) {
        this.maxImageWidth = value;
    }

    /**
     * Gets the value of the maxImageHeight property.
     * 
     */
    public int getMaxImageHeight() {
        return maxImageHeight;
    }

    /**
     * Sets the value of the maxImageHeight property.
     * 
     */
    public void setMaxImageHeight(int value) {
        this.maxImageHeight = value;
    }

    /**
     * Gets the value of the blockProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalSettingsType.BlockProfiles }
     *     
     */
    public GlobalSettingsType.BlockProfiles getBlockProfiles() {
        return blockProfiles;
    }

    /**
     * Sets the value of the blockProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalSettingsType.BlockProfiles }
     *     
     */
    public void setBlockProfiles(GlobalSettingsType.BlockProfiles value) {
        this.blockProfiles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="blockProfile" type="{http://www.example.org/pluginSettings}blockProfileType" maxOccurs="unbounded"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "blockProfile"
    })
    public static class BlockProfiles {

        @XmlElement(required = true)
        protected List<BlockProfileType> blockProfile;

        /**
         * Gets the value of the blockProfile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the blockProfile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBlockProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BlockProfileType }
         * 
         * 
         * @return
         *     The value of the blockProfile property.
         */
        public List<BlockProfileType> getBlockProfile() {
            if (blockProfile == null) {
                blockProfile = new ArrayList<>();
            }
            return this.blockProfile;
        }

    }

}
