//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.bukkitmodders.copycat.config;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bukkitmodders.copycat.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigFile_QNAME = new QName("http://www.example.org/pluginSettings", "configFile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bukkitmodders.copycat.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BlockProfileType }
     * 
     * @return
     *     the new instance of {@link BlockProfileType }
     */
    public BlockProfileType createBlockProfileType() {
        return new BlockProfileType();
    }

    /**
     * Create an instance of {@link PlayerSettingsType }
     * 
     * @return
     *     the new instance of {@link PlayerSettingsType }
     */
    public PlayerSettingsType createPlayerSettingsType() {
        return new PlayerSettingsType();
    }

    /**
     * Create an instance of {@link PlayerSettingsType.Shortcuts }
     * 
     * @return
     *     the new instance of {@link PlayerSettingsType.Shortcuts }
     */
    public PlayerSettingsType.Shortcuts createPlayerSettingsTypeShortcuts() {
        return new PlayerSettingsType.Shortcuts();
    }

    /**
     * Create an instance of {@link GlobalSettingsType }
     * 
     * @return
     *     the new instance of {@link GlobalSettingsType }
     */
    public GlobalSettingsType createGlobalSettingsType() {
        return new GlobalSettingsType();
    }

    /**
     * Create an instance of {@link PluginConfig }
     * 
     * @return
     *     the new instance of {@link PluginConfig }
     */
    public PluginConfig createPluginConfig() {
        return new PluginConfig();
    }

    /**
     * Create an instance of {@link BlockProfileType.Block }
     * 
     * @return
     *     the new instance of {@link BlockProfileType.Block }
     */
    public BlockProfileType.Block createBlockProfileTypeBlock() {
        return new BlockProfileType.Block();
    }

    /**
     * Create an instance of {@link PlayerSettingsType.Shortcuts.Shortcut }
     * 
     * @return
     *     the new instance of {@link PlayerSettingsType.Shortcuts.Shortcut }
     */
    public PlayerSettingsType.Shortcuts.Shortcut createPlayerSettingsTypeShortcutsShortcut() {
        return new PlayerSettingsType.Shortcuts.Shortcut();
    }

    /**
     * Create an instance of {@link GlobalSettingsType.BlockProfiles }
     * 
     * @return
     *     the new instance of {@link GlobalSettingsType.BlockProfiles }
     */
    public GlobalSettingsType.BlockProfiles createGlobalSettingsTypeBlockProfiles() {
        return new GlobalSettingsType.BlockProfiles();
    }

    /**
     * Create an instance of {@link PluginConfig.Preferences }
     * 
     * @return
     *     the new instance of {@link PluginConfig.Preferences }
     */
    public PluginConfig.Preferences createPluginConfigPreferences() {
        return new PluginConfig.Preferences();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PluginConfig }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PluginConfig }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.org/pluginSettings", name = "configFile")
    public JAXBElement<PluginConfig> createConfigFile(PluginConfig value) {
        return new JAXBElement<>(_ConfigFile_QNAME, PluginConfig.class, null, value);
    }

}
