//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.bukkitmodders.copycat.config;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for playerSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="playerSettingsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="blockProfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="buildWidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="buildHeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="activeShortcut" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="stampItem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="undoEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="dithering" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="shortcuts">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="shortcut" maxOccurs="unbounded" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           <attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="playerName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="stampActivated" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "playerSettingsType", propOrder = {
    "blockProfile",
    "buildWidth",
    "buildHeight",
    "activeShortcut",
    "stampItem",
    "undoEnabled",
    "dithering",
    "shortcuts"
})
public class PlayerSettingsType {

    @XmlElement(required = true)
    protected String blockProfile;
    @XmlElement(defaultValue = "64")
    protected int buildWidth;
    @XmlElement(defaultValue = "64")
    protected int buildHeight;
    @XmlElement(required = true)
    protected String activeShortcut;
    @XmlElement(required = true)
    protected String stampItem;
    protected boolean undoEnabled;
    @XmlElement(defaultValue = "true")
    protected boolean dithering;
    @XmlElement(required = true)
    protected PlayerSettingsType.Shortcuts shortcuts;
    @XmlAttribute(name = "playerName", required = true)
    protected String playerName;
    @XmlAttribute(name = "stampActivated", required = true)
    protected boolean stampActivated;

    /**
     * Gets the value of the blockProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockProfile() {
        return blockProfile;
    }

    /**
     * Sets the value of the blockProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockProfile(String value) {
        this.blockProfile = value;
    }

    /**
     * Gets the value of the buildWidth property.
     * 
     */
    public int getBuildWidth() {
        return buildWidth;
    }

    /**
     * Sets the value of the buildWidth property.
     * 
     */
    public void setBuildWidth(int value) {
        this.buildWidth = value;
    }

    /**
     * Gets the value of the buildHeight property.
     * 
     */
    public int getBuildHeight() {
        return buildHeight;
    }

    /**
     * Sets the value of the buildHeight property.
     * 
     */
    public void setBuildHeight(int value) {
        this.buildHeight = value;
    }

    /**
     * Gets the value of the activeShortcut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveShortcut() {
        return activeShortcut;
    }

    /**
     * Sets the value of the activeShortcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveShortcut(String value) {
        this.activeShortcut = value;
    }

    /**
     * Gets the value of the stampItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStampItem() {
        return stampItem;
    }

    /**
     * Sets the value of the stampItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStampItem(String value) {
        this.stampItem = value;
    }

    /**
     * Gets the value of the undoEnabled property.
     * 
     */
    public boolean isUndoEnabled() {
        return undoEnabled;
    }

    /**
     * Sets the value of the undoEnabled property.
     * 
     */
    public void setUndoEnabled(boolean value) {
        this.undoEnabled = value;
    }

    /**
     * Gets the value of the dithering property.
     * 
     */
    public boolean isDithering() {
        return dithering;
    }

    /**
     * Sets the value of the dithering property.
     * 
     */
    public void setDithering(boolean value) {
        this.dithering = value;
    }

    /**
     * Gets the value of the shortcuts property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerSettingsType.Shortcuts }
     *     
     */
    public PlayerSettingsType.Shortcuts getShortcuts() {
        return shortcuts;
    }

    /**
     * Sets the value of the shortcuts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerSettingsType.Shortcuts }
     *     
     */
    public void setShortcuts(PlayerSettingsType.Shortcuts value) {
        this.shortcuts = value;
    }

    /**
     * Gets the value of the playerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

    /**
     * Gets the value of the stampActivated property.
     * 
     */
    public boolean isStampActivated() {
        return stampActivated;
    }

    /**
     * Sets the value of the stampActivated property.
     * 
     */
    public void setStampActivated(boolean value) {
        this.stampActivated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="shortcut" maxOccurs="unbounded" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 <attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shortcut"
    })
    public static class Shortcuts {

        protected List<PlayerSettingsType.Shortcuts.Shortcut> shortcut;

        /**
         * Gets the value of the shortcut property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the shortcut property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShortcut().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlayerSettingsType.Shortcuts.Shortcut }
         * 
         * 
         * @return
         *     The value of the shortcut property.
         */
        public List<PlayerSettingsType.Shortcuts.Shortcut> getShortcut() {
            if (shortcut == null) {
                shortcut = new ArrayList<>();
            }
            return this.shortcut;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       <attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Shortcut {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "url", required = true)
            protected String url;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }

    }

}
