//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.bukkitmodders.copycat.config;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pluginConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="pluginConfig">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="globalSettings" type="{http://www.example.org/pluginSettings}globalSettingsType"/>
 *         <element name="preferences">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="playerPreferences" type="{http://www.example.org/pluginSettings}playerSettingsType" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pluginConfig", propOrder = {
    "globalSettings",
    "preferences"
})
public class PluginConfig {

    @XmlElement(required = true)
    protected GlobalSettingsType globalSettings;
    @XmlElement(required = true)
    protected PluginConfig.Preferences preferences;

    /**
     * Gets the value of the globalSettings property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalSettingsType }
     *     
     */
    public GlobalSettingsType getGlobalSettings() {
        return globalSettings;
    }

    /**
     * Sets the value of the globalSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalSettingsType }
     *     
     */
    public void setGlobalSettings(GlobalSettingsType value) {
        this.globalSettings = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link PluginConfig.Preferences }
     *     
     */
    public PluginConfig.Preferences getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginConfig.Preferences }
     *     
     */
    public void setPreferences(PluginConfig.Preferences value) {
        this.preferences = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="playerPreferences" type="{http://www.example.org/pluginSettings}playerSettingsType" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "playerPreferences"
    })
    public static class Preferences {

        protected List<PlayerSettingsType> playerPreferences;

        /**
         * Gets the value of the playerPreferences property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the playerPreferences property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlayerPreferences().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlayerSettingsType }
         * 
         * 
         * @return
         *     The value of the playerPreferences property.
         */
        public List<PlayerSettingsType> getPlayerPreferences() {
            if (playerPreferences == null) {
                playerPreferences = new ArrayList<>();
            }
            return this.playerPreferences;
        }

    }

}
