name: Copycat
version: 1.0
main: org.bukkitmodders.copycat.Nouveau
api-version: '1.21'
commands:
  ccimg:
    description: Image command
    usage: /ccimg <args>
  ccset:
    description: Set command
    usage: /ccset <args>
  ccadmin:
    description: Admin command
    usage: /ccadmin <args>
  ccstamp:
    description: Stamp command
    usage: /ccstamp <args>
  cc:
    description: CC command
    usage: /cc <args>
