name: Copycat
version: 1.0
main: org.bukkitmodders.copycat.Nouveau
api-version: '1.21'
commands:
  ccimg:
    description: Image command
    usage: /ccimg <args>
    permission: copycat.img
  ccset:
    description: Set command
    usage: /ccset <args>
    permission: copycat.set
  ccadmin:
    description: Admin command
    usage: /ccadmin <args>
    permission: copycat.admin
  ccstamp:
    description: Stamp command
    usage: /ccstamp <args>
    permission: copycat.stamp
  cc:
    description: CC command
    usage: /cc <args>
    permission: copycat.use

permissions:
  copycat.img:
    description: Allows use of image commands
    default: true
  copycat.set:
    description: Allows use of set commands
    default: true
  copycat.admin:
    description: Allows use of admin commands
    default: op
  copycat.stamp:
    description: Allows use of stamp commands
    default: true
  copycat.use:
    description: Allows use of basic CC commands
    default: true
  copycat.*:
    description: Grants access to all Copycat commands
    default: op
    children:
      copycat.img: true
      copycat.set: true
      copycat.admin: true
      copycat.stamp: true
      copycat.use: true