//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.13 at 01:56:52 PM CDT 
//


package org.bukkitmodders.copycat.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bukkitmodders.copycat.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigFile_QNAME = new QName("http://www.example.org/pluginSettings", "configFile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bukkitmodders.copycat.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GlobalSettingsType.BlockProfiles }
     * 
     */
    public GlobalSettingsType.BlockProfiles createGlobalSettingsTypeBlockProfiles() {
        return new GlobalSettingsType.BlockProfiles();
    }

    /**
     * Create an instance of {@link GlobalSettingsType.ProhibitedWorlds }
     * 
     */
    public GlobalSettingsType.ProhibitedWorlds createGlobalSettingsTypeProhibitedWorlds() {
        return new GlobalSettingsType.ProhibitedWorlds();
    }

    /**
     * Create an instance of {@link PlayerSettingsType.Shortcuts }
     * 
     */
    public PlayerSettingsType.Shortcuts createPlayerSettingsTypeShortcuts() {
        return new PlayerSettingsType.Shortcuts();
    }

    /**
     * Create an instance of {@link PlayerSettingsType }
     * 
     */
    public PlayerSettingsType createPlayerSettingsType() {
        return new PlayerSettingsType();
    }

    /**
     * Create an instance of {@link GlobalSettingsType }
     * 
     */
    public GlobalSettingsType createGlobalSettingsType() {
        return new GlobalSettingsType();
    }

    /**
     * Create an instance of {@link BlockProfileType }
     * 
     */
    public BlockProfileType createBlockProfileType() {
        return new BlockProfileType();
    }

    /**
     * Create an instance of {@link PlayerSettingsType.Shortcuts.Shortcut }
     * 
     */
    public PlayerSettingsType.Shortcuts.Shortcut createPlayerSettingsTypeShortcutsShortcut() {
        return new PlayerSettingsType.Shortcuts.Shortcut();
    }

    /**
     * Create an instance of {@link BlockProfileType.Block }
     * 
     */
    public BlockProfileType.Block createBlockProfileTypeBlock() {
        return new BlockProfileType.Block();
    }

    /**
     * Create an instance of {@link PluginConfig }
     * 
     */
    public PluginConfig createPluginConfig() {
        return new PluginConfig();
    }

    /**
     * Create an instance of {@link PluginConfig.Preferences }
     * 
     */
    public PluginConfig.Preferences createPluginConfigPreferences() {
        return new PluginConfig.Preferences();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PluginConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/pluginSettings", name = "configFile")
    public JAXBElement<PluginConfig> createConfigFile(PluginConfig value) {
        return new JAXBElement<PluginConfig>(_ConfigFile_QNAME, PluginConfig.class, null, value);
    }

}
