//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.12 at 08:12:51 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/pluginSettings")
package org.bukkitmodders.copycat.schema;
