//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.13 at 01:56:52 PM CDT 
//


package org.bukkitmodders.copycat.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for playerSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="playerSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="blockProfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildWidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="buildHeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="shortcuts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="shortcut" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="playerName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="playerEnabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "playerSettingsType", propOrder = {
    "blockProfile",
    "buildWidth",
    "buildHeight",
    "shortcuts"
})
public class PlayerSettingsType {

    @XmlElement(required = true)
    protected String blockProfile;
    @XmlElement(defaultValue = "64")
    protected int buildWidth;
    @XmlElement(defaultValue = "64")
    protected int buildHeight;
    @XmlElement(required = true)
    protected PlayerSettingsType.Shortcuts shortcuts;
    @XmlAttribute(name = "playerName", required = true)
    protected String playerName;
    @XmlAttribute(name = "playerEnabled", required = true)
    protected boolean playerEnabled;

    /**
     * Gets the value of the blockProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockProfile() {
        return blockProfile;
    }

    /**
     * Sets the value of the blockProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockProfile(String value) {
        this.blockProfile = value;
    }

    /**
     * Gets the value of the buildWidth property.
     * 
     */
    public int getBuildWidth() {
        return buildWidth;
    }

    /**
     * Sets the value of the buildWidth property.
     * 
     */
    public void setBuildWidth(int value) {
        this.buildWidth = value;
    }

    /**
     * Gets the value of the buildHeight property.
     * 
     */
    public int getBuildHeight() {
        return buildHeight;
    }

    /**
     * Sets the value of the buildHeight property.
     * 
     */
    public void setBuildHeight(int value) {
        this.buildHeight = value;
    }

    /**
     * Gets the value of the shortcuts property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerSettingsType.Shortcuts }
     *     
     */
    public PlayerSettingsType.Shortcuts getShortcuts() {
        return shortcuts;
    }

    /**
     * Sets the value of the shortcuts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerSettingsType.Shortcuts }
     *     
     */
    public void setShortcuts(PlayerSettingsType.Shortcuts value) {
        this.shortcuts = value;
    }

    /**
     * Gets the value of the playerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

    /**
     * Gets the value of the playerEnabled property.
     * 
     */
    public boolean isPlayerEnabled() {
        return playerEnabled;
    }

    /**
     * Sets the value of the playerEnabled property.
     * 
     */
    public void setPlayerEnabled(boolean value) {
        this.playerEnabled = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="shortcut" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shortcut"
    })
    public static class Shortcuts {

        protected List<PlayerSettingsType.Shortcuts.Shortcut> shortcut;

        /**
         * Gets the value of the shortcut property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shortcut property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShortcut().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlayerSettingsType.Shortcuts.Shortcut }
         * 
         * 
         */
        public List<PlayerSettingsType.Shortcuts.Shortcut> getShortcut() {
            if (shortcut == null) {
                shortcut = new ArrayList<PlayerSettingsType.Shortcuts.Shortcut>();
            }
            return this.shortcut;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Shortcut {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "url", required = true)
            protected String url;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }

    }

}
