//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.06 at 08:25:44 PM CDT 
//


package org.bukkitmodders.copycat.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pluginConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pluginConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="globalSettings" type="{http://www.example.org/pluginSettings}globalSettingsType"/>
 *         &lt;element name="preferences">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="playerPreferences" type="{http://www.example.org/pluginSettings}playerSettingsType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pluginConfig", propOrder = {
    "globalSettings",
    "preferences"
})
public class PluginConfig {

    @XmlElement(required = true)
    protected GlobalSettingsType globalSettings;
    @XmlElement(required = true)
    protected PluginConfig.Preferences preferences;

    /**
     * Gets the value of the globalSettings property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalSettingsType }
     *     
     */
    public GlobalSettingsType getGlobalSettings() {
        return globalSettings;
    }

    /**
     * Sets the value of the globalSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalSettingsType }
     *     
     */
    public void setGlobalSettings(GlobalSettingsType value) {
        this.globalSettings = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link PluginConfig.Preferences }
     *     
     */
    public PluginConfig.Preferences getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginConfig.Preferences }
     *     
     */
    public void setPreferences(PluginConfig.Preferences value) {
        this.preferences = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="playerPreferences" type="{http://www.example.org/pluginSettings}playerSettingsType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "playerPreferences"
    })
    public static class Preferences {

        protected List<PlayerSettingsType> playerPreferences;

        /**
         * Gets the value of the playerPreferences property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the playerPreferences property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlayerPreferences().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlayerSettingsType }
         * 
         * 
         */
        public List<PlayerSettingsType> getPlayerPreferences() {
            if (playerPreferences == null) {
                playerPreferences = new ArrayList<PlayerSettingsType>();
            }
            return this.playerPreferences;
        }

    }

}
