//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.20 at 07:38:43 PM PDT 
//


package org.bukkitmodders.copycat.schema;

import java.util.ArrayList;
import java.util.List;

public class GlobalSettingsType {

    protected int maxImageWidth;
    protected int maxImageHeight;
    protected GlobalSettingsType.BlockProfiles blockProfiles;

    /**
     * Gets the value of the maxImageWidth property.
     * 
     */
    public int getMaxImageWidth() {
        return maxImageWidth;
    }

    /**
     * Sets the value of the maxImageWidth property.
     * 
     */
    public void setMaxImageWidth(int value) {
        this.maxImageWidth = value;
    }

    /**
     * Gets the value of the maxImageHeight property.
     * 
     */
    public int getMaxImageHeight() {
        return maxImageHeight;
    }

    /**
     * Sets the value of the maxImageHeight property.
     * 
     */
    public void setMaxImageHeight(int value) {
        this.maxImageHeight = value;
    }

    /**
     * Gets the value of the blockProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link BlockProfiles }
     *     
     */
    public BlockProfiles getBlockProfiles() {
        return blockProfiles;
    }

    /**
     * Sets the value of the blockProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockProfiles }
     *     
     */
    public void setBlockProfiles(BlockProfiles value) {
        this.blockProfiles = value;
    }


    public static class BlockProfiles {

        protected List<BlockProfileType> blockProfile;

        /**
         * Gets the value of the blockProfile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the blockProfile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBlockProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BlockProfileType }
         * 
         * 
         */
        public List<BlockProfileType> getBlockProfile() {
            if (blockProfile == null) {
                blockProfile = new ArrayList<BlockProfileType>();
            }
            return this.blockProfile;
        }
    }
}
